services:
  web:
    container_name: k13-fullstack
    image: node:22.9.0
    working_dir: /app/web
    user: "1000:1000"
    volumes:
      - ./react/:/app/web
    ports:
      - '3000:3000'
    command: [ "npm", "run", "dev", "--", "--port", "3000" ]