services:
  api:
    container_name: f8-k13-api
    image: node:22.9.0
    working_dir: /app/api
    volumes:
      - ./api:/app/api
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    command: ['npm', 'run', 'start:dev']

  db:
    container_name: f8-k13-db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - '5000:5432'
    volumes:
      - ./db:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${PROJECT_NAME}_mailhog
    volumes:
      - ./data/mail:/maildir:cached
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/maildir
    ports:
      - "1025:1025"
      - "8025:8025"